from lib2to3.pgen2 import driver
from selenium import webdriver
from selenium.common import NoSuchElementException
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import NoSuchElementException
chrome_options = Options()
chrome_options.add_argument("--disable-notifications")
chrome_options.add_argument("--disable-infobars")
chrome_options.add_argument("--start-maximized")
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service, options=chrome_options)
driver.get("https://mvpdev.factory360.tech/admin/authentication")
driver.get('https://mvpdev.factory360.tech/admin/')
email_input = driver.find_element(By.ID, "email")
email_input.send_keys("sadmin@gmail.com")
password_input = driver.find_element(By.NAME, "password")
password_input.send_keys("admin#@123")
driver.find_element(By.XPATH, "//button[contains(text(), 'Đăng nhập')]").click()
time.sleep(6)
# driver.find_element(By.CLASS_NAME, "hide-menu").click()
setup_button = driver.find_element(By.ID, "setup-menu-item")
driver.execute_script("arguments[0].scrollIntoView();", setup_button)
time.sleep(2)
setup_button.click()
driver.find_element(By.ID, "setup-menu-item").click()
menu_vi_tri = driver.find_element(By.CLASS_NAME, "menu-item-roles")

actions = ActionChains(driver)
actions.move_to_element(menu_vi_tri).click().perform()
driver.find_element(By.CLASS_NAME, "menu-item-roles").click()
time.sleep(4)

test = ['bulk_pdf_exporter_view',
    'contracts_view_own', 'contracts_view', 'contracts_create', 'contracts_edit', 'contracts_delete', 'contracts_view_all_templates',
    'credit_notes_view_own', 'credit_notes_view', 'credit_notes_create', 'credit_notes_edit', 'credit_notes_delete',
    'customers_view_own', 'customers_view', 'customers_create', 'customers_edit', 'customers_delete',
    'email_templates_view', 'email_templates_edit'
        ]
# row_bulk_pdf_exporter = driver.find_element(By.XPATH, "//tr[@data-name='bulk_pdf_exporter']")
All = [
    'bulk_pdf_exporter_view',
    'contracts_view_own', 'contracts_view', 'contracts_create', 'contracts_edit', 'contracts_delete', 'contracts_view_all_templates',
    'credit_notes_view_own', 'credit_notes_view', 'credit_notes_create', 'credit_notes_edit', 'credit_notes_delete',
    'customers_view_own', 'customers_view', 'customers_create', 'customers_edit', 'customers_delete',
    'email_templates_view', 'email_templates_edit',
    'estimates_view_own', 'estimates_view', 'estimates_create', 'estimates_edit', 'estimates_delete',
    'expenses_view_own', 'expenses_view', 'expenses_create', 'expenses_edit', 'expenses_delete',
    'invoices_view_own', 'invoices_view', 'invoices_create', 'invoices_edit', 'invoices_delete',
    'items_view', 'items_create', 'items_edit', 'items_delete',
    'knowledge_base_view', 'knowledge_base_create', 'knowledge_base_edit', 'knowledge_base_delete',
    'payments_view_own', 'payments_view', 'payments_create', 'payments_edit', 'payments_delete',
    'projects_view_own', 'projects_view', 'projects_create', 'projects_edit', 'projects_delete',
    'projects_create_milestones', 'projects_edit_milestones', 'projects_delete_milestones',
    'proposals_view_own', 'proposals_view', 'proposals_create', 'proposals_edit', 'proposals_delete', 'proposals_view_all_templates',
    'reports_view', 'reports_view-timesheets',
    'roles_view', 'roles_create', 'roles_edit', 'roles_delete',
    'settings_view', 'settings_edit',
    'staff_view', 'staff_create', 'staff_edit', 'staff_delete',
    'subscriptions_view_own', 'subscriptions_view', 'subscriptions_create', 'subscriptions_edit', 'subscriptions_delete',
    'tasks_view_own', 'tasks_view', 'tasks_create', 'tasks_edit', 'tasks_delete',
    'tasks_edit_timesheet', 'tasks_edit_own_timesheet', 'tasks_delete_timesheet', 'tasks_delete_own_timesheet',
    'checklist_templates_create', 'checklist_templates_delete',
    'estimate_request_view_own', 'estimate_request_view', 'estimate_request_create', 'estimate_request_edit', 'estimate_request_delete',
    'leads_view', 'leads_delete',
    'translations_view', 'translations_create', 'translations_edit',
    'goals_view', 'goals_create', 'goals_edit', 'goals_delete',
    'hrp_employee_view_own', 'hrp_employee_view', 'hrp_employee_create', 'hrp_employee_edit', 'hrp_employee_delete',
    'hrp_attendance_view_own', 'hrp_attendance_view', 'hrp_attendance_create', 'hrp_attendance_edit', 'hrp_attendance_delete',
    'hrp_commission_view_own', 'hrp_commission_view', 'hrp_commission_create', 'hrp_commission_edit', 'hrp_commission_delete',
    'hrp_deduction_view_own', 'hrp_deduction_view', 'hrp_deduction_create', 'hrp_deduction_edit', 'hrp_deduction_delete',
    'hrp_bonus_kpi_view_own', 'hrp_bonus_kpi_view', 'hrp_bonus_kpi_create', 'hrp_bonus_kpi_edit', 'hrp_bonus_kpi_delete',
    'hrp_insurrance_view_own', 'hrp_insurrance_view', 'hrp_insurrance_create', 'hrp_insurrance_edit', 'hrp_insurrance_delete',
    'hrp_payslip_view_own', 'hrp_payslip_view', 'hrp_payslip_create', 'hrp_payslip_edit', 'hrp_payslip_delete',
    'hrp_payslip_template_view_own', 'hrp_payslip_template_view', 'hrp_payslip_template_create', 'hrp_payslip_template_edit', 'hrp_payslip_template_delete',
    'hrp_income_tax_view_own', 'hrp_income_tax_view',
    'hrp_report_view',
    'hrp_setting_view','hrp_setting_view', 'hrp_setting_create', 'hrp_setting_edit', 'hrp_setting_delete',
    'importsync_view', 'importsync_create', 'importsync_edit', 'importsync_delete', 'importsync_import_staff',
    'mention_view',
    'prchat_view',
    'purchase_items_view', 'purchase_items_create', 'purchase_items_edit', 'purchase_items_delete',
    'purchase_vendors_view', 'purchase_vendors_create', 'purchase_vendors_edit', 'purchase_vendors_delete',
    'purchase_vendor_items_view', 'purchase_vendor_items_create', 'purchase_vendor_items_edit', 'purchase_vendor_items_delete',
    'purchase_request_view', 'purchase_request_create', 'purchase_request_edit', 'purchase_request_delete',
    'purchase_quotations_view', 'purchase_quotations_create', 'purchase_quotations_edit', 'purchase_quotations_delete',
    'purchase_orders_view', 'purchase_orders_create', 'purchase_orders_edit', 'purchase_orders_delete',
    'purchase_order_return_view', 'purchase_order_return_create', 'purchase_order_return_edit', 'purchase_order_return_delete',
    'purchase_contracts_view', 'purchase_contracts_create', 'purchase_contracts_edit', 'purchase_contracts_delete',
    'purchase_invoices_view', 'purchase_invoices_create', 'purchase_invoices_edit', 'purchase_invoices_delete',
    'purchase_debit_notes_view', 'purchase_debit_notes_create', 'purchase_debit_notes_edit', 'purchase_debit_notes_delete',
    'purchase_reports_view',
    'pw_rp_resource_workload_view',
    'warehouse_view', 'warehouse_create', 'warehouse_edit', 'warehouse_delete',
    'omni_sales_view', 'omni_sales_view_order_list', 'omni_sales_view_sales_channel', 'omni_sales_view_trade_discount',
    'omni_sales_view_diary_sync', 'omni_sales_view_report', 'omni_sales_view_pos',
    'perfex_saas_dashboard_view',
    'perfex_saas_companies_view', 'perfex_saas_companies_create', 'perfex_saas_companies_edit', 'perfex_saas_companies_delete',
    'perfex_saas_packages_view', 'perfex_saas_packages_create', 'perfex_saas_packages_edit', 'perfex_saas_packages_delete',
    'perfex_saas_api_user_view', 'perfex_saas_api_user_create', 'perfex_saas_api_user_edit', 'perfex_saas_api_user_delete',
    'perfex_saas_settings_view', 'perfex_saas_settings_edit',
    'hrm_dashboard_view',
    'staffmanage_orgchart_view_own', 'staffmanage_orgchart_view', 'staffmanage_orgchart_create', 'staffmanage_orgchart_edit', 'staffmanage_orgchart_delete',
    'hrm_reception_staff_view_own', 'hrm_reception_staff_view', 'hrm_reception_staff_create', 'hrm_reception_staff_edit', 'hrm_reception_staff_delete',
    'hrm_hr_records_view_own', 'hrm_hr_records_view', 'hrm_hr_records_create', 'hrm_hr_records_edit', 'hrm_hr_records_delete',
    'staffmanage_job_position_view_own', 'staffmanage_job_position_view', 'staffmanage_job_position_create', 'staffmanage_job_position_edit', 'staffmanage_job_position_delete',
    'staffmanage_training_view_own', 'staffmanage_training_view', 'staffmanage_training_create', 'staffmanage_training_edit', 'staffmanage_training_delete',
    'hr_manage_q_a_view', 'hr_manage_q_a_create', 'hr_manage_q_a_edit', 'hr_manage_q_a_delete',
    'hrm_contract_view_own', 'hrm_contract_view', 'hrm_contract_create', 'hrm_contract_edit', 'hrm_contract_delete',
    'hrm_dependent_person_view_own', 'hrm_dependent_person_view', 'hrm_dependent_person_create', 'hrm_dependent_person_edit', 'hrm_dependent_person_delete',
    'hrm_procedures_for_quitting_work_view_own', 'hrm_procedures_for_quitting_work_view', 'hrm_procedures_for_quitting_work_create',
    'hrm_procedures_for_quitting_work_edit', 'hrm_procedures_for_quitting_work_delete',
    'hrm_report_view',
    'hrm_setting_view', 'hrm_setting_create', 'hrm_setting_edit', 'hrm_setting_delete',
    'attendance_management_view_own', 'attendance_management_view',
    'leave_management_view_own', 'leave_management_view',
    'route_management_view_own', 'route_management_view',
    'additional_timesheets_management_view_own', 'additional_timesheets_management_view',
    'table_shiftwork_management_view_own', 'table_shiftwork_management_view',
    'report_management_view_own', 'report_management_view',
    'table_workplace_management_view_own', 'table_workplace_management_view',
    'okr_view_own', 'okr_view', 'okr_create', 'okr_edit', 'okr_delete'
]
Admin = [
    'bulk_pdf_exporter_view',
     'contracts_view', 'contracts_create', 'contracts_edit', 'contracts_delete', 'contracts_view_all_templates',
     'credit_notes_view', 'credit_notes_create', 'credit_notes_edit', 'credit_notes_delete',
    'customers_view', 'customers_create', 'customers_edit', 'customers_delete',
    'email_templates_view', 'email_templates_edit',
     'estimates_view', 'estimates_create', 'estimates_edit', 'estimates_delete',
     'expenses_view', 'expenses_create', 'expenses_edit', 'expenses_delete',
     'invoices_view', 'invoices_create', 'invoices_edit', 'invoices_delete',
    'items_view', 'items_create', 'items_edit', 'items_delete',
    'knowledge_base_view', 'knowledge_base_create', 'knowledge_base_edit', 'knowledge_base_delete',
    'payments_view', 'payments_create', 'payments_edit', 'payments_delete',
     'projects_view', 'projects_create', 'projects_edit', 'projects_delete',
    'projects_create_milestones', 'projects_edit_milestones', 'projects_delete_milestones',
     'proposals_view', 'proposals_create', 'proposals_edit', 'proposals_delete', 'proposals_view_all_templates',
    'reports_view', 'reports_view-timesheets',
    'roles_view', 'roles_create', 'roles_edit', 'roles_delete',
    'settings_view', 'settings_edit',
    'staff_view', 'staff_create', 'staff_edit', 'staff_delete',
     'subscriptions_view', 'subscriptions_create', 'subscriptions_edit', 'subscriptions_delete',
     'tasks_view', 'tasks_create', 'tasks_edit', 'tasks_delete',
    'tasks_edit_timesheet', 'tasks_edit_own_timesheet', 'tasks_delete_timesheet', 'tasks_delete_own_timesheet',
    'checklist_templates_create', 'checklist_templates_delete',
     'estimate_request_view', 'estimate_request_create', 'estimate_request_edit', 'estimate_request_delete',
    'leads_view', 'leads_delete',
    'translations_view', 'translations_create', 'translations_edit',
    'goals_view', 'goals_create', 'goals_edit', 'goals_delete',
    'hrp_employee_view', 'hrp_employee_create', 'hrp_employee_edit', 'hrp_employee_delete',
    'hrp_attendance_view', 'hrp_attendance_create', 'hrp_attendance_edit', 'hrp_attendance_delete',
     'hrp_commission_view', 'hrp_commission_create', 'hrp_commission_edit', 'hrp_commission_delete',
    'hrp_deduction_view', 'hrp_deduction_create', 'hrp_deduction_edit', 'hrp_deduction_delete',
    'hrp_bonus_kpi_view', 'hrp_bonus_kpi_create', 'hrp_bonus_kpi_edit', 'hrp_bonus_kpi_delete',
     'hrp_insurrance_view', 'hrp_insurrance_create', 'hrp_insurrance_edit', 'hrp_insurrance_delete',
     'hrp_payslip_view', 'hrp_payslip_create', 'hrp_payslip_edit', 'hrp_payslip_delete',
     'hrp_payslip_template_view', 'hrp_payslip_template_create', 'hrp_payslip_template_edit', 'hrp_payslip_template_delete',
     'hrp_income_tax_view',
    'hrp_report_view',
    'hrp_setting_view', 'hrp_setting_create', 'hrp_setting_edit', 'hrp_setting_delete',
    'importsync_view', 'importsync_create', 'importsync_edit', 'importsync_delete', 'importsync_import_staff',
    'mention_view',
    'prchat_view',
    'purchase_items_view', 'purchase_items_create', 'purchase_items_edit', 'purchase_items_delete',
    'purchase_vendors_view', 'purchase_vendors_create', 'purchase_vendors_edit', 'purchase_vendors_delete',
    'purchase_vendor_items_view', 'purchase_vendor_items_create', 'purchase_vendor_items_edit', 'purchase_vendor_items_delete',
    'purchase_request_view', 'purchase_request_create', 'purchase_request_edit', 'purchase_request_delete',
    'purchase_quotations_view', 'purchase_quotations_create', 'purchase_quotations_edit', 'purchase_quotations_delete',
    'purchase_orders_view', 'purchase_orders_create', 'purchase_orders_edit', 'purchase_orders_delete',
    'purchase_order_return_view', 'purchase_order_return_create', 'purchase_order_return_edit', 'purchase_order_return_delete',
    'purchase_contracts_view', 'purchase_contracts_create', 'purchase_contracts_edit', 'purchase_contracts_delete',
    'purchase_invoices_view', 'purchase_invoices_create', 'purchase_invoices_edit', 'purchase_invoices_delete',
    'purchase_debit_notes_view', 'purchase_debit_notes_create', 'purchase_debit_notes_edit', 'purchase_debit_notes_delete',
    'purchase_reports_view',
    'pw_rp_resource_workload_view',
    'warehouse_view', 'warehouse_create', 'warehouse_edit', 'warehouse_delete',
    'omni_sales_view', 'omni_sales_view_order_list', 'omni_sales_view_sales_channel', 'omni_sales_view_trade_discount',
    'omni_sales_view_diary_sync', 'omni_sales_view_report', 'omni_sales_view_pos',
    'perfex_saas_dashboard_view',
    'perfex_saas_companies_view', 'perfex_saas_companies_create', 'perfex_saas_companies_edit', 'perfex_saas_companies_delete',
    'perfex_saas_packages_view', 'perfex_saas_packages_create', 'perfex_saas_packages_edit', 'perfex_saas_packages_delete',
    'perfex_saas_api_user_view', 'perfex_saas_api_user_create', 'perfex_saas_api_user_edit', 'perfex_saas_api_user_delete',
    'perfex_saas_settings_view', 'perfex_saas_settings_edit',
    'hrm_dashboard_view',
    'staffmanage_orgchart_view', 'staffmanage_orgchart_create', 'staffmanage_orgchart_edit', 'staffmanage_orgchart_delete',
     'hrm_reception_staff_view', 'hrm_reception_staff_create', 'hrm_reception_staff_edit', 'hrm_reception_staff_delete',
    'hrm_hr_records_view', 'hrm_hr_records_create', 'hrm_hr_records_edit', 'hrm_hr_records_delete',
     'staffmanage_job_position_view', 'staffmanage_job_position_create', 'staffmanage_job_position_edit', 'staffmanage_job_position_delete',
     'staffmanage_training_view', 'staffmanage_training_create', 'staffmanage_training_edit', 'staffmanage_training_delete',
    'hr_manage_q_a_view', 'hr_manage_q_a_create', 'hr_manage_q_a_edit', 'hr_manage_q_a_delete',
     'hrm_contract_view', 'hrm_contract_create', 'hrm_contract_edit', 'hrm_contract_delete',
     'hrm_dependent_person_view', 'hrm_dependent_person_create', 'hrm_dependent_person_edit', 'hrm_dependent_person_delete',
     'hrm_procedures_for_quitting_work_view', 'hrm_procedures_for_quitting_work_create', 'hrm_procedures_for_quitting_work_edit', 'hrm_procedures_for_quitting_work_delete',
    'hrm_report_view',
    'hrm_setting_view', 'hrm_setting_create', 'hrm_setting_edit', 'hrm_setting_delete',
     'attendance_management_view',
     'leave_management_view',
     'route_management_view',
     'additional_timesheets_management_view',
     'table_shiftwork_management_view',
    'report_management_view',
    'table_workplace_management_view',
     'okr_view', 'okr_create', 'okr_edit', 'okr_delete'
]
Sales_Admin= [
    'bulk_pdf_exporter_view',
     'contracts_view', 'contracts_create', 'contracts_edit', 'contracts_delete', 'contracts_view_all_templates',
     'credit_notes_view', 'credit_notes_create', 'credit_notes_edit', 'credit_notes_delete',
    'customers_view', 'customers_create', 'customers_edit', 'customers_delete',
    'email_templates_view', 'email_templates_edit',
     'estimates_view', 'estimates_create', 'estimates_edit', 'estimates_delete',
     'invoices_view', 'invoices_create', 'invoices_edit', 'invoices_delete',
    'items_view',
    'payments_view', 'payments_create', 'payments_edit', 'payments_delete',
     'proposals_view', 'proposals_create', 'proposals_edit', 'proposals_delete', 'proposals_view_all_templates',
    'reports_view', 'reports_view-timesheets',
    'roles_view',
    'staff_view',
     'subscriptions_view', 'subscriptions_create', 'subscriptions_edit', 'subscriptions_delete',
     'tasks_view', 'tasks_create', 'tasks_edit', 'tasks_delete',
    'tasks_edit_timesheet', 'tasks_edit_own_timesheet', 'tasks_delete_timesheet', 'tasks_delete_own_timesheet',
    'checklist_templates_create', 'checklist_templates_delete',
    'leads_view', 'leads_delete',
    'goals_view', 'goals_create', 'goals_edit', 'goals_delete',
    'hrp_employee_view',
    'hrp_attendance_view',
     'hrp_commission_view', 'hrp_commission_create', 'hrp_commission_edit', 'hrp_commission_delete',
    'hrp_deduction_view',
    'hrp_bonus_kpi_view', 'hrp_bonus_kpi_create', 'hrp_bonus_kpi_edit', 'hrp_bonus_kpi_delete',
     'hrp_insurrance_view',
     'hrp_payslip_view',
     'hrp_income_tax_view',
    'mention_view',
    'prchat_view',
    'pw_rp_resource_workload_view',
    'warehouse_view',
    'staffmanage_orgchart_view',
     'hrm_reception_staff_view',
    'hrm_hr_records_view',
     'staffmanage_job_position_view',
     'staffmanage_training_view', 'staffmanage_training_create', 'staffmanage_training_edit', 'staffmanage_training_delete',
    'hr_manage_q_a_view', 'hr_manage_q_a_create', 'hr_manage_q_a_edit', 'hr_manage_q_a_delete',
     'hrm_contract_view_own',
     'hrm_dependent_person_view_own',
     'hrm_procedures_for_quitting_work_view', 'hrm_procedures_for_quitting_work_create', 'hrm_procedures_for_quitting_work_edit', 'hrm_procedures_for_quitting_work_delete',
    'hrm_setting_view', 'hrm_setting_create', 'hrm_setting_edit', 'hrm_setting_delete',
     'attendance_management_view',
     'leave_management_view',
     'route_management_view',
     'additional_timesheets_management_view',
     'table_shiftwork_management_view',
    'table_workplace_management_view',
     'okr_view_own'
]
Sales= [
    'bulk_pdf_exporter_view',
    'contracts_view_own', 'contracts_create', 'contracts_edit', 'contracts_delete', 'contracts_view_all_templates',
    'credit_notes_view_own',  'credit_notes_create', 'credit_notes_edit', 'credit_notes_delete',
     'customers_view', 'customers_create', 'customers_edit', 'customers_delete',
    'email_templates_view', 'email_templates_edit',
    'estimates_view_own',  'estimates_create', 'estimates_edit', 'estimates_delete',
    'invoices_view_own',  'invoices_create', 'invoices_edit', 'invoices_delete',
    'items_view',
    'payments_view_own',  'payments_create', 'payments_edit', 'payments_delete',
    'proposals_view_own', 'proposals_create', 'proposals_edit', 'proposals_delete', 'proposals_view_all_templates',
    'staff_view',
    'subscriptions_view_own', 'subscriptions_create', 'subscriptions_edit', 'subscriptions_delete',
    'tasks_view_own',
    'leads_view', 'leads_delete',
    'goals_view',
    'hrp_employee_view_own',
    'hrp_attendance_view_own',
    'hrp_commission_view_own',
    'hrp_deduction_view_own',
    'hrp_bonus_kpi_view_own',
    'hrp_insurrance_view_own',
    'hrp_payslip_view_own',
    'hrp_income_tax_view_own',
    'mention_view',
    'staffmanage_orgchart_view_own',
    'hrm_reception_staff_view_own',
    'hrm_hr_records_view_own',
    'staffmanage_job_position_view_own',
    'staffmanage_training_view_own',
    'hrm_contract_view_own',
    'hrm_dependent_person_view_own',
    'hrm_procedures_for_quitting_work_view_own',
    'attendance_management_view_own',
    'leave_management_view_own',
    'route_management_view_own',
    'additional_timesheets_management_view_own',
    'table_shiftwork_management_view_own',
    'report_management_view_own',
    'table_workplace_management_view_own',
    'okr_view_own'
]
Marketing_Manager = [
    'bulk_pdf_exporter_view',
     'contracts_view',
    'customers_view', 'customers_create', 'customers_edit', 'customers_delete',
    'email_templates_view', 'email_templates_edit',
     'invoices_view', 'invoices_create', 'invoices_edit', 'invoices_delete',
    'items_view',
     'proposals_view', 'proposals_create', 'proposals_edit', 'proposals_delete', 'proposals_view_all_templates',
    'reports_view', 'reports_view-timesheets',
    'roles_view',
    'staff_view',
     'tasks_view', 'tasks_create', 'tasks_edit', 'tasks_delete',
    'tasks_edit_timesheet', 'tasks_edit_own_timesheet', 'tasks_delete_timesheet', 'tasks_delete_own_timesheet',
    'checklist_templates_create', 'checklist_templates_delete',
    'leads_view', 'leads_delete',
    'goals_view', 'goals_create', 'goals_edit', 'goals_delete',
    'hrp_employee_view',
    'hrp_attendance_view',
     'hrp_commission_view', 'hrp_commission_create', 'hrp_commission_edit', 'hrp_commission_delete',
    'hrp_deduction_view',
    'hrp_bonus_kpi_view', 'hrp_bonus_kpi_create', 'hrp_bonus_kpi_edit', 'hrp_bonus_kpi_delete',
     'hrp_insurrance_view',
     'hrp_payslip_view',
     'hrp_income_tax_view',
    'mention_view',
    'prchat_view',
    'pw_rp_resource_workload_view',
    'warehouse_view',
    'staffmanage_orgchart_view',
     'hrm_reception_staff_view',
    'hrm_hr_records_view',
     'staffmanage_job_position_view',
     'staffmanage_training_view', 'staffmanage_training_create', 'staffmanage_training_edit', 'staffmanage_training_delete',
    'hr_manage_q_a_view', 'hr_manage_q_a_create', 'hr_manage_q_a_edit', 'hr_manage_q_a_delete',
     'hrm_contract_view_own',
     'hrm_dependent_person_view_own',
     'hrm_procedures_for_quitting_work_view', 'hrm_procedures_for_quitting_work_create', 'hrm_procedures_for_quitting_work_edit', 'hrm_procedures_for_quitting_work_delete',
    'hrm_setting_view', 'hrm_setting_create', 'hrm_setting_edit', 'hrm_setting_delete',
     'attendance_management_view',
     'leave_management_view',
     'route_management_view',
     'additional_timesheets_management_view',
     'table_shiftwork_management_view',
    'table_workplace_management_view',
     'okr_view_own'
]
Marketing =[
    'bulk_pdf_exporter_view',
    'contracts_view_own', 'contracts_create', 'contracts_edit', 'contracts_delete', 'contracts_view_all_templates',
    'credit_notes_view_own',  'credit_notes_create', 'credit_notes_edit', 'credit_notes_delete',
     'customers_view', 'customers_create', 'customers_edit', 'customers_delete',
    'email_templates_view', 'email_templates_edit',
    'invoices_view_own',  'invoices_create', 'invoices_edit', 'invoices_delete',
    'items_view',
    'proposals_view_own', 'proposals_create', 'proposals_edit', 'proposals_delete', 'proposals_view_all_templates',
    'staff_view',
    'tasks_view_own',
    'goals_view',
    'hrp_employee_view_own',
    'hrp_attendance_view_own',
    'hrp_commission_view_own',
    'hrp_deduction_view_own',
    'hrp_bonus_kpi_view_own',
    'hrp_insurrance_view_own',
    'hrp_payslip_view_own',
    'hrp_income_tax_view_own',
    'mention_view',
    'staffmanage_orgchart_view_own',
    'hrm_reception_staff_view_own',
    'hrm_hr_records_view_own',
    'staffmanage_job_position_view_own',
    'staffmanage_training_view_own',
    'hrm_contract_view_own',
    'hrm_dependent_person_view_own',
    'hrm_procedures_for_quitting_work_view_own',
    'attendance_management_view_own',
    'leave_management_view_own',
    'route_management_view_own',
    'additional_timesheets_management_view_own',
    'table_shiftwork_management_view_own',
    'report_management_view_own',
    'table_workplace_management_view_own',
    'okr_view_own'
]
Accounting =[
    'bulk_pdf_exporter_view',
     'contracts_view', 'contracts_create', 'contracts_edit', 'contracts_delete', 'contracts_view_all_templates',
     'credit_notes_view', 'credit_notes_create', 'credit_notes_edit', 'credit_notes_delete',
    'customers_view', 'customers_create', 'customers_edit', 'customers_delete',
    'email_templates_view', 'email_templates_edit',
     'estimates_view', 'estimates_create', 'estimates_edit', 'estimates_delete',
     'expenses_view', 'expenses_create', 'expenses_edit', 'expenses_delete',
     'invoices_view', 'invoices_create', 'invoices_edit', 'invoices_delete',
    'items_view', 'items_create', 'items_edit', 'items_delete',
    'payments_view', 'payments_create', 'payments_edit', 'payments_delete',
    'reports_view', 'reports_view-timesheets',
    'roles_view',
    'staff_view',
     'subscriptions_view', 'subscriptions_create', 'subscriptions_edit', 'subscriptions_delete',
     'tasks_view', 'tasks_create', 'tasks_edit', 'tasks_delete',
    'tasks_edit_timesheet', 'tasks_edit_own_timesheet', 'tasks_delete_timesheet', 'tasks_delete_own_timesheet',
    'goals_view',
    'hrp_employee_view', 'hrp_employee_create', 'hrp_employee_edit', 'hrp_employee_delete',
    'hrp_attendance_view', 'hrp_attendance_create', 'hrp_attendance_edit', 'hrp_attendance_delete',
     'hrp_commission_view', 'hrp_commission_create', 'hrp_commission_edit', 'hrp_commission_delete',
    'hrp_deduction_view', 'hrp_deduction_create', 'hrp_deduction_edit', 'hrp_deduction_delete',
    'hrp_bonus_kpi_view', 'hrp_bonus_kpi_create', 'hrp_bonus_kpi_edit', 'hrp_bonus_kpi_delete',
     'hrp_insurrance_view', 'hrp_insurrance_create', 'hrp_insurrance_edit', 'hrp_insurrance_delete',
     'hrp_payslip_view', 'hrp_payslip_create', 'hrp_payslip_edit', 'hrp_payslip_delete',
     'hrp_payslip_template_view', 'hrp_payslip_template_create', 'hrp_payslip_template_edit', 'hrp_payslip_template_delete',
     'hrp_income_tax_view',
    'hrp_report_view',
    'hrp_setting_view', 'hrp_setting_create', 'hrp_setting_edit', 'hrp_setting_delete',
    'importsync_view', 'importsync_create', 'importsync_edit', 'importsync_delete', 'importsync_import_staff',
    'mention_view',
    'prchat_view',
    'purchase_items_view',
    'purchase_vendors_view', 'purchase_vendors_create', 'purchase_vendors_edit', 'purchase_vendors_delete',
    'purchase_vendor_items_view', 'purchase_vendor_items_create', 'purchase_vendor_items_edit', 'purchase_vendor_items_delete',
    'purchase_request_view', 'purchase_request_create', 'purchase_request_edit', 'purchase_request_delete',
    'purchase_quotations_view', 'purchase_quotations_create', 'purchase_quotations_edit', 'purchase_quotations_delete',
    'purchase_orders_view', 'purchase_orders_create', 'purchase_orders_edit', 'purchase_orders_delete',
    'purchase_order_return_view', 'purchase_order_return_create', 'purchase_order_return_edit', 'purchase_order_return_delete',
    'purchase_contracts_view', 'purchase_contracts_create', 'purchase_contracts_edit', 'purchase_contracts_delete',
    'purchase_invoices_view', 'purchase_invoices_create', 'purchase_invoices_edit', 'purchase_invoices_delete',
    'purchase_debit_notes_view', 'purchase_debit_notes_create', 'purchase_debit_notes_edit', 'purchase_debit_notes_delete',
    'purchase_reports_view',
    'pw_rp_resource_workload_view',
    'warehouse_view',
    'staffmanage_orgchart_view',
     'hrm_reception_staff_view',
    'hrm_hr_records_view',
     'staffmanage_job_position_view',
     'staffmanage_training_view',
    'hr_manage_q_a_view',
     'hrm_contract_view', 'hrm_contract_create', 'hrm_contract_edit', 'hrm_contract_delete',
     'hrm_dependent_person_view', 'hrm_dependent_person_create', 'hrm_dependent_person_edit', 'hrm_dependent_person_delete',
     'hrm_procedures_for_quitting_work_view', 'hrm_procedures_for_quitting_work_create', 'hrm_procedures_for_quitting_work_edit', 'hrm_procedures_for_quitting_work_delete',
     'attendance_management_view',
     'leave_management_view',
     'route_management_view',
     'additional_timesheets_management_view',
     'table_shiftwork_management_view',
    'table_workplace_management_view',
     'okr_view',
]
Manager =[
    'bulk_pdf_exporter_view',
    'contracts_view_own', 'contracts_create', 'contracts_edit', 'contracts_delete', 'contracts_view_all_templates',
    'customers_view',
    'email_templates_view', 'email_templates_edit',
    'items_view',
    'knowledge_base_view', 'knowledge_base_create', 'knowledge_base_edit', 'knowledge_base_delete',
     'projects_view', 'projects_create', 'projects_edit', 'projects_delete',
    'projects_create_milestones', 'projects_edit_milestones', 'projects_delete_milestones',
     'proposals_view', 'proposals_create', 'proposals_edit', 'proposals_delete', 'proposals_view_all_templates',
    'reports_view', 'reports_view-timesheets',
    'settings_view', 'settings_edit',
    'staff_view', 'staff_create', 'staff_edit', 'staff_delete',
     'tasks_view', 'tasks_create', 'tasks_edit', 'tasks_delete',
    'tasks_edit_timesheet', 'tasks_edit_own_timesheet', 'tasks_delete_timesheet', 'tasks_delete_own_timesheet',
    'checklist_templates_create', 'checklist_templates_delete',
     'estimate_request_view', 'estimate_request_create', 'estimate_request_edit', 'estimate_request_delete',
    'goals_view',
    'hrp_employee_view_own',
    'hrp_attendance_view_own',
     'hrp_commission_view_own',
    'hrp_deduction_view_own',
    'hrp_bonus_kpi_view_own',
     'hrp_insurrance_view_own',
     'hrp_payslip_view_own',
     'hrp_income_tax_view_own',
    'mention_view',
    'hrm_dashboard_view',
    'staffmanage_orgchart_view', 'staffmanage_orgchart_create', 'staffmanage_orgchart_edit', 'staffmanage_orgchart_delete',
     'hrm_reception_staff_view', 'hrm_reception_staff_create', 'hrm_reception_staff_edit', 'hrm_reception_staff_delete',
    'hrm_hr_records_view', 'hrm_hr_records_create', 'hrm_hr_records_edit', 'hrm_hr_records_delete',
     'staffmanage_job_position_view', 'staffmanage_job_position_create', 'staffmanage_job_position_edit', 'staffmanage_job_position_delete',
     'staffmanage_training_view', 'staffmanage_training_create', 'staffmanage_training_edit', 'staffmanage_training_delete',
    'hr_manage_q_a_view', 'hr_manage_q_a_create', 'hr_manage_q_a_edit', 'hr_manage_q_a_delete',
     'hrm_contract_view_own',
     'hrm_dependent_person_view_own',
     'hrm_procedures_for_quitting_work_view_own',
    'hrm_report_view_own',
     'attendance_management_view',
     'leave_management_view',
     'route_management_view',
     'additional_timesheets_management_view',
     'table_shiftwork_management_view',
    'table_workplace_management_view',
     'okr_view'
]
Engineer =[
    'bulk_pdf_exporter_view',
    'contracts_view_own',
    'items_view',
    'knowledge_base_view'
     'projects_view_own'
    'staff_view',
     'tasks_view', 'tasks_create', 'tasks_edit', 'tasks_delete', 'tasks_edit_own_timesheet',  'tasks_delete_own_timesheet',
    'hrp_employee_view_own',
    'hrp_attendance_view_own',
     'hrp_commission_view_own',
    'hrp_deduction_view_own',
    'hrp_bonus_kpi_view_own',
     'hrp_insurrance_view_own',
     'hrp_payslip_view_own',
     'hrp_income_tax_view_own',
    'mention_view',
     'hrm_reception_staff_view_own',
    'hrm_hr_records_view_own',
     'staffmanage_job_position_view_own',
     'staffmanage_training_view_own',
    'hr_manage_q_a_view',
     'hrm_contract_view_own',
     'attendance_management_view',
     'leave_management_view'
]
Human_Resources_Manager = [
    'bulk_pdf_exporter_view',
     'contracts_view', 'contracts_create', 'contracts_edit', 'contracts_delete', 'contracts_view_all_templates',
    'customers_view',
    'email_templates_view', 'email_templates_edit',
     'expenses_view', 'expenses_create', 'expenses_edit', 'expenses_delete',
     'invoices_view', 'invoices_create', 'invoices_edit', 'invoices_delete',
    'items_view',
    'knowledge_base_view', 'knowledge_base_create', 'knowledge_base_edit', 'knowledge_base_delete',
    'payments_view', 'payments_create', 'payments_edit', 'payments_delete',
     'projects_view', 'projects_create', 'projects_edit', 'projects_delete',
    'projects_create_milestones', 'projects_edit_milestones', 'projects_delete_milestones',
     'proposals_view', 'proposals_create', 'proposals_edit', 'proposals_delete', 'proposals_view_all_templates',
    'reports_view', 'reports_view-timesheets',
    'roles_view', 'roles_create', 'roles_edit', 'roles_delete',
    'settings_view', 'settings_edit',
    'staff_view', 'staff_create', 'staff_edit', 'staff_delete',
     'subscriptions_view', 'subscriptions_create', 'subscriptions_edit', 'subscriptions_delete',
     'tasks_view', 'tasks_create', 'tasks_edit', 'tasks_delete',
    'tasks_edit_timesheet', 'tasks_edit_own_timesheet', 'tasks_delete_timesheet', 'tasks_delete_own_timesheet',
    'checklist_templates_create', 'checklist_templates_delete',
     'estimate_request_view', 'estimate_request_create', 'estimate_request_edit', 'estimate_request_delete',
    'leads_view', 'leads_delete',
    'translations_view', 'translations_create', 'translations_edit',
    'goals_view', 'goals_create', 'goals_edit', 'goals_delete',
    'hrp_employee_view', 'hrp_employee_create', 'hrp_employee_edit', 'hrp_employee_delete',
    'hrp_attendance_view', 'hrp_attendance_create', 'hrp_attendance_edit', 'hrp_attendance_delete',
     'hrp_commission_view', 'hrp_commission_create', 'hrp_commission_edit', 'hrp_commission_delete',
    'hrp_deduction_view', 'hrp_deduction_create', 'hrp_deduction_edit', 'hrp_deduction_delete',
    'hrp_bonus_kpi_view', 'hrp_bonus_kpi_create', 'hrp_bonus_kpi_edit', 'hrp_bonus_kpi_delete',
     'hrp_insurrance_view', 'hrp_insurrance_create', 'hrp_insurrance_edit', 'hrp_insurrance_delete',
     'hrp_payslip_view', 'hrp_payslip_create', 'hrp_payslip_edit', 'hrp_payslip_delete',
     'hrp_payslip_template_view', 'hrp_payslip_template_create', 'hrp_payslip_template_edit', 'hrp_payslip_template_delete',
     'hrp_income_tax_view',
    'hrp_report_view',
    'hrp_setting_view', 'hrp_setting_create', 'hrp_setting_edit', 'hrp_setting_delete',
    'importsync_view', 'importsync_create', 'importsync_edit', 'importsync_delete', 'importsync_import_staff',
    'mention_view',
    'prchat_view',
    'purchase_items_view', 'purchase_items_create', 'purchase_items_edit', 'purchase_items_delete',
    'purchase_vendors_view', 'purchase_vendors_create', 'purchase_vendors_edit', 'purchase_vendors_delete',
    'purchase_vendor_items_view', 'purchase_vendor_items_create', 'purchase_vendor_items_edit', 'purchase_vendor_items_delete',
    'purchase_request_view', 'purchase_request_create', 'purchase_request_edit', 'purchase_request_delete',
    'purchase_quotations_view', 'purchase_quotations_create', 'purchase_quotations_edit', 'purchase_quotations_delete',
    'purchase_orders_view', 'purchase_orders_create', 'purchase_orders_edit', 'purchase_orders_delete',
    'purchase_order_return_view', 'purchase_order_return_create', 'purchase_order_return_edit', 'purchase_order_return_delete',
    'purchase_contracts_view', 'purchase_contracts_create', 'purchase_contracts_edit', 'purchase_contracts_delete',
    'purchase_invoices_view', 'purchase_invoices_create', 'purchase_invoices_edit', 'purchase_invoices_delete',
    'purchase_debit_notes_view', 'purchase_debit_notes_create', 'purchase_debit_notes_edit', 'purchase_debit_notes_delete',
    'purchase_reports_view',
    'pw_rp_resource_workload_view',
    'warehouse_view', 'warehouse_create', 'warehouse_edit', 'warehouse_delete',
    'omni_sales_view', 'omni_sales_view_order_list', 'omni_sales_view_sales_channel', 'omni_sales_view_trade_discount',
    'omni_sales_view_diary_sync', 'omni_sales_view_report', 'omni_sales_view_pos',
    'perfex_saas_dashboard_view',
    'perfex_saas_companies_view', 'perfex_saas_companies_create', 'perfex_saas_companies_edit', 'perfex_saas_companies_delete',
    'perfex_saas_packages_view', 'perfex_saas_packages_create', 'perfex_saas_packages_edit', 'perfex_saas_packages_delete',
    'perfex_saas_api_user_view', 'perfex_saas_api_user_create', 'perfex_saas_api_user_edit', 'perfex_saas_api_user_delete',
    'perfex_saas_settings_view', 'perfex_saas_settings_edit',
    'hrm_dashboard_view',
    'staffmanage_orgchart_view', 'staffmanage_orgchart_create', 'staffmanage_orgchart_edit', 'staffmanage_orgchart_delete',
     'hrm_reception_staff_view', 'hrm_reception_staff_create', 'hrm_reception_staff_edit', 'hrm_reception_staff_delete',
    'hrm_hr_records_view', 'hrm_hr_records_create', 'hrm_hr_records_edit', 'hrm_hr_records_delete',
     'staffmanage_job_position_view', 'staffmanage_job_position_create', 'staffmanage_job_position_edit', 'staffmanage_job_position_delete',
     'staffmanage_training_view', 'staffmanage_training_create', 'staffmanage_training_edit', 'staffmanage_training_delete',
    'hr_manage_q_a_view', 'hr_manage_q_a_create', 'hr_manage_q_a_edit', 'hr_manage_q_a_delete',
     'hrm_contract_view', 'hrm_contract_create', 'hrm_contract_edit', 'hrm_contract_delete',
     'hrm_dependent_person_view', 'hrm_dependent_person_create', 'hrm_dependent_person_edit', 'hrm_dependent_person_delete',
     'hrm_procedures_for_quitting_work_view', 'hrm_procedures_for_quitting_work_create', 'hrm_procedures_for_quitting_work_edit', 'hrm_procedures_for_quitting_work_delete',
    'hrm_report_view',
    'hrm_setting_view', 'hrm_setting_create', 'hrm_setting_edit', 'hrm_setting_delete',
     'attendance_management_view',
     'leave_management_view',
     'route_management_view',
     'additional_timesheets_management_view',
     'table_shiftwork_management_view',
    'report_management_view',
    'table_workplace_management_view',
     'okr_view', 'okr_create', 'okr_edit', 'okr_delete'
]
Warehouse_Staff =[
     'contracts_view_own', 'contracts_create', 'contracts_edit', 'contracts_delete', 'contracts_view_all_templates',
    'email_templates_view', 'email_templates_edit',
     'invoices_view', 'invoices_create', 'invoices_edit', 'invoices_delete',
    'items_view', 'items_create', 'items_edit', 'items_delete',
    'payments_view', 'payments_create', 'payments_edit', 'payments_delete',
    'staff_view_own',
     'tasks_view', 'tasks_create', 'tasks_edit', 'tasks_delete',
    'tasks_edit_timesheet', 'tasks_edit_own_timesheet', 'tasks_delete_timesheet', 'tasks_delete_own_timesheet',
    'hrp_employee_view_own',
    'hrp_attendance_view_own',
    'hrp_commission_view_own',
    'hrp_deduction_view_own',
    'hrp_bonus_kpi_view_own',
    'hrp_insurrance_view_own',
    'hrp_payslip_view_own',
    'hrp_income_tax_view_own',
    'mention_view',
    'prchat_view',
    'purchase_items_view',
    'purchase_vendors_view', 'purchase_vendors_create', 'purchase_vendors_edit', 'purchase_vendors_delete',
    'purchase_vendor_items_view', 'purchase_vendor_items_create', 'purchase_vendor_items_edit', 'purchase_vendor_items_delete',
    'purchase_request_view', 'purchase_request_create', 'purchase_request_edit', 'purchase_request_delete',
    'purchase_quotations_view', 'purchase_quotations_create', 'purchase_quotations_edit', 'purchase_quotations_delete',
    'purchase_orders_view', 'purchase_orders_create', 'purchase_orders_edit', 'purchase_orders_delete',
    'purchase_order_return_view', 'purchase_order_return_create', 'purchase_order_return_edit', 'purchase_order_return_delete',
    'purchase_contracts_view', 'purchase_contracts_create', 'purchase_contracts_edit', 'purchase_contracts_delete',
    'purchase_invoices_view', 'purchase_invoices_create', 'purchase_invoices_edit', 'purchase_invoices_delete',
    'purchase_debit_notes_view', 'purchase_debit_notes_create', 'purchase_debit_notes_edit', 'purchase_debit_notes_delete',
    'purchase_reports_view',
    'pw_rp_resource_workload_view',
    'warehouse_view',
     'hrm_reception_staff_view_own',
    'hrm_hr_records_view_own',
     'staffmanage_job_position_view_own',
     'staffmanage_training_view_own',
    'hr_manage_q_a_view',
     'hrm_contract_view_own',
     'attendance_management_view',
     'leave_management_view'
]
Customer_Support_Staff =[
    'bulk_pdf_exporter_view',
     'contracts_view', 'contracts_create', 'contracts_edit', 'contracts_delete', 'contracts_view_all_templates',
     'credit_notes_view', 'credit_notes_create', 'credit_notes_edit', 'credit_notes_delete',
    'customers_view', 'customers_create', 'customers_edit', 'customers_delete',
    'email_templates_view', 'email_templates_edit',
     'invoices_view', 'invoices_create', 'invoices_edit', 'invoices_delete',
    'items_view',
    'payments_view', 'payments_create', 'payments_edit', 'payments_delete',
    'staff_view',
     'subscriptions_view', 'subscriptions_create', 'subscriptions_edit', 'subscriptions_delete',
    'hrp_employee_view_own',
    'hrp_attendance_view_own',
     'hrp_commission_view_own',
    'hrp_deduction_view_own',
    'hrp_bonus_kpi_view_own',
     'hrp_insurrance_view_own',
     'hrp_payslip_view_own',
     'hrp_income_tax_view_own',
      'mention_view',
     'hrm_reception_staff_view_own',
    'hrm_hr_records_view_own',
     'staffmanage_job_position_view_own',
     'staffmanage_training_view_own',
    'hr_manage_q_a_view',
     'hrm_contract_view_own',
     'attendance_management_view',
     'leave_management_view'
]
# checkbox = driver.find_element(By.ID, 'bulk_pdf_exporter_view')
# # label = driver.find_element(By.XPATH, "//label[@for='bulk_pdf_exporter_view']")
# if not checkbox.is_selected():
#     checkbox.click()
driver.find_element(By.XPATH, "//*[@id='wrapper']/div/div/div/div[1]/a/i").click()
driver.find_element(By.ID, "name").send_keys("Warehouse Staff")
for permission in Warehouse_Staff:
    try:
        checkbox = driver.find_element(By.ID, permission)
        if not checkbox.is_selected():
            checkbox.click()
            print(f"Đã chọn: {permission}")
        else:
            print(f"Đã được chọn trước: {permission}")
    except Exception as e:
        print(f"Lỗi khi xử lý {permission}: {e}")
driver.find_element(By.XPATH, "//button[contains(text(), 'Lưu lại')]").click()
time.sleep(10)
driver.quit()
driver.close()